export const WAVEFORM_HOT_ZONE_RATIO = 0.15;
export const WAVEFORM_MAX_SPEED_RATIO = 0.005;
export const WAVEFORM_DRAG_ZOOM_VIEWPORT_RATIO = 0.5;
export const WAVEFORM_SCROLL_SHIFT_MULTIPLIER = 0.5;
export const WAVEFORM_ZOOM_STEP = 20;
export const WAVEFORM_ZOOM_MAX = 500;
export const WAVEFORM_REGION_OPACITY_HEX = '26';
export const WAVEFORM_MIN_SPEED_FACTOR = 0.2;
